services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 3456:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/posgresql/data

  ngcash-back-end:
    container_name: ngcash-back-end
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres: